### ISSUE TITLE
how to use with angularJS

### ISSUE THREAD

**Issue by Simplici** [hellsan631/material-avatar#4]
Hello,

I have seen your super package material avatar on NPM.

I want to use it in my angular application.

I add this to my controller:

 `MaterialAvatar(document.getElementsByClass('default-profile-photo'), options);
`
But it does not seem to work, I have following error:

<img width="1437" alt="2016-04-04 11 05 02" src="https://cloud.githubusercontent.com/assets/8101111/14263392/9d1fc036-faba-11e5-90e7-42a605db9cb4.png">

Do you have any idea about this error?

Thanks very much.

**Comment by hellsan631** [comment]
AngularJS renders the dom differently. Basically, when the controller hits, the dom can remain unrendered. The error your getting means that the element itself isn't actually on screen. What you want to do is use the material-avatar inside a directive.

Here is some code of how I use it:

Directive JS file

``` js
(function () {
  'use strict';

  angular
    .module('myApp') //what ever your module is named
    .directive('materialAvatar', avatar);

  avatar.$inject = ['$window'];

  /* @ngInject */
  function avatar($window) {
    var directive = {
      restrict: 'A',
      scope: {
        options: '='
      },
      link: link
    };

    return directive;

    function link(scope, element) {

      //we are creating the new element here and sending in our options
      var options = scope.options || {};
      var avatarElement = new MaterialAvatar(element, options);

      scope.$watch('options', function(options) {
        if (options) {
          avatarElement.updateOptions(options);
        }
      });
    }
  }
})();
```

What the HTML useage looks like

``` html
<div material-avatar options="avatarOptions">
   {{ name }}
</div>
```

What the controller would look like:

``` js
function Controller($scope){
  $scope.avatarOptions = {
    shape: 'circle',
    backgroundColor: '#61ccd3',
    textColor: '#fff',
    fontFamily: 'Lato-Regular',
    fontSize: 22
  };
}
```

**Comment by Simplici** [comment]
Thanks very much for this detailed response.

**Comment by Simplici** [comment]
I have tried your proposition for angularJS, it works. But I found something strange: the letter is not centered. 
![image](https://cloud.githubusercontent.com/assets/8101111/16468986/e79ea118-3e4e-11e6-8ecd-d5e27c88492e.png)

**Comment by hellsan631** [comment]
it looks like the font that's being might be causing the issue. that or the font size. try using a different font the I specified above.
